version: '3'
services: 
  mysql-node:
    image: mysql
    build: ./mysql
    container_name: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=socnet
    ports:
      - 3306:3306  
    networks:
     - socnet
     
  redis:
    image: 'bitnami/redis:latest'
    container_name: "redis"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
    #volumes:
   #   - 'redis_data:/bitnami/redis'
    networks:
     - socnet      
 
  
networks:
  socnet:
    driver: overlay